# Generated by Django 2.2.27 on 2022-02-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil',
            new_name='email',
        ),
    ]
